name: Latest book list from goodreads
on:
  schedule: # Run workflow automatically every hour
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with I'm currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "40441560"
          shelf: "read"
          max_books_count: "5"
          template: "- [$title]($url) by $author ($my_rating_stars)"
