name: Last 10 books from a goodreads
on:
  schedule: # Run workflow automatically
    # This will make it run every night at 10:05PM
    - cron: "5 22 * * *"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books-read:
    name: Update this repo's README with the last 5 books you've read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "40441560"
          shelf: "read"
          comment_tag_name: "GOODREADS-READ-LIST"
          max_books_count: "10"
          template: "- [$title]($url) by $author ($my_rating_stars)"
